# Generated by Django 2.2.5 on 2019-09-25 11:49

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ManagementCommandLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "app_name",
                    models.CharField(
                        help_text="The app containing the management command",
                        max_length=100,
                    ),
                ),
                (
                    "command_name",
                    models.CharField(
                        help_text="The management command that was executed",
                        max_length=100,
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField()),
                (
                    "exit_code",
                    models.IntegerField(
                        default=0, help_text="0 if the command ran without error."
                    ),
                ),
                (
                    "result",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True,
                        default=dict,
                        help_text="The return value of the command (must be JSON serializable)",
                        null=True,
                    ),
                ),
            ],
        )
    ]
