# Generated by Django 3.0.2 on 2020-04-25 13:39

from django.db import migrations, models

from command_log.models import ManagementCommandLog


class Migration(migrations.Migration):

    dependencies = [
        ("command_log", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="managementcommandlog",
            name="error",
            field=models.TextField(
                blank=True, default="", help_text="Any error output captured"
            ),
        ),
        migrations.AlterField(
            model_name="managementcommandlog",
            name="output",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The output of the command (stored as a string)",
            ),
        ),
        migrations.AlterField(
            model_name="managementcommandlog",
            name="exit_code",
            field=models.IntegerField(
                blank=True,
                choices=ManagementCommandLog.EXIT_CODE_CHOICES,
                default=None,
                help_text="0 if the command ran without error.",
                null=True,
            ),
        ),
    ]
